swagger: '2.0'
basePath: /
paths:
  /Stores/:
    get:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/store_list'
      operationId: get_stores
      tags:
        - Stores
  '/Stores/store/{identifier}':
    parameters:
      - in: path
        description: The store number
        name: identifier
        required: true
        type: string
    get:
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/store'
        '404':
          description: Not Found
      operationId: get_store
      tags:
        - Stores
    post:
      responses:
        '201':
          description: Store Created Successfully
        '401':
          description: Store Not Created
      operationId: post_store
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/store'
      tags:
        - Stores
    put:
      responses:
        '200':
          description: Success
      operationId: put_store
      parameters:
        - name: payload
          required: true
          in: body
          schema:
            $ref: '#/definitions/store'
      tags:
        - Stores
info:
  title: Store API
  version: 0.01.0
  description: Sample usage of flask_restplus
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: default
    description: Default namespace
  - name: Stores
    description: API for store level access
definitions:
  store_list:
    properties:
      stores:
        type: array
        items:
          $ref: '#/definitions/store'
    type: object
  store:
    properties:
      identifier:
        type: string
      Address_Line_1:
        type: string
      Address_Line_2:
        type: string
      Zip:
        type: string
      State:
        type: string
      Registers:
        type: array
        items:
          $ref: '#/definitions/register'
    type: object
  register:
    properties:
      identifier:
        type: string
      balance:
        type: number
    type: object
